// Generated by gencpp from file beginner_tutorials/add_two_numbers.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_ADD_TWO_NUMBERS_H
#define BEGINNER_TUTORIALS_MESSAGE_ADD_TWO_NUMBERS_H

#include <ros/service_traits.h>


#include <beginner_tutorials/add_two_numbersRequest.h>
#include <beginner_tutorials/add_two_numbersResponse.h>


namespace beginner_tutorials
{

struct add_two_numbers
{

typedef add_two_numbersRequest Request;
typedef add_two_numbersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct add_two_numbers
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::add_two_numbers > {
  static const char* value()
  {
    return "875493d2ec8f0bdc18c62960322c94b7";
  }

  static const char* value(const ::beginner_tutorials::add_two_numbers&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::add_two_numbers > {
  static const char* value()
  {
    return "beginner_tutorials/add_two_numbers";
  }

  static const char* value(const ::beginner_tutorials::add_two_numbers&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::add_two_numbersRequest> should match
// service_traits::MD5Sum< ::beginner_tutorials::add_two_numbers >
template<>
struct MD5Sum< ::beginner_tutorials::add_two_numbersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::add_two_numbers >::value();
  }
  static const char* value(const ::beginner_tutorials::add_two_numbersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::add_two_numbersRequest> should match
// service_traits::DataType< ::beginner_tutorials::add_two_numbers >
template<>
struct DataType< ::beginner_tutorials::add_two_numbersRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::add_two_numbers >::value();
  }
  static const char* value(const ::beginner_tutorials::add_two_numbersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::add_two_numbersResponse> should match
// service_traits::MD5Sum< ::beginner_tutorials::add_two_numbers >
template<>
struct MD5Sum< ::beginner_tutorials::add_two_numbersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::add_two_numbers >::value();
  }
  static const char* value(const ::beginner_tutorials::add_two_numbersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::add_two_numbersResponse> should match
// service_traits::DataType< ::beginner_tutorials::add_two_numbers >
template<>
struct DataType< ::beginner_tutorials::add_two_numbersResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::add_two_numbers >::value();
  }
  static const char* value(const ::beginner_tutorials::add_two_numbersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_ADD_TWO_NUMBERS_H
